// Regenerates tokens.js from the contents of images-optimized/ (falls back to images/
// if optimize hasn't been run yet). Add or remove a file in that folder, then rerun this.
// Run: npm run tokens

const fs = require("fs");
const path = require("path");

const OPTIMIZED_DIR = path.join(__dirname, "..", "images-optimized");
const FALLBACK_DIR = path.join(__dirname, "..", "images");
const OUT_FILE = path.join(__dirname, "..", "js", "tokens.js");
const IMG_RE = /\.(webp|png|jpe?g)$/i;

function main() {
  const dir = fs.existsSync(OPTIMIZED_DIR) ? OPTIMIZED_DIR : FALLBACK_DIR;
  const files = fs
    .readdirSync(dir)
    .filter((f) => IMG_RE.test(f))
    .sort((a, b) => a.localeCompare(b));

  const entries = files
    .map((file) => {
      const name = file.replace(IMG_RE, "");
      return `  { name: ${JSON.stringify(name)}, file: ${JSON.stringify(file)} },`;
    })
    .join("\n");

  const contents = `// Generated by scripts/generate-tokens.js from ${path.basename(dir)}/ — do not edit by hand.
// Add or remove images in that folder, then run: npm run tokens
const TOKENS = [
${entries}
];
`;

  fs.writeFileSync(OUT_FILE, contents);
  console.log(`Wrote ${files.length} tokens to ${OUT_FILE} (source: ${path.basename(dir)}/)`);
}

main();
