// Regenerates tokens.js from the contents of images-optimized/<Style>/ (falls back to
// images/<Style>/ if optimize hasn't been run yet). One array per art style — see
// ALLOWED_STYLES in worker/src/config.js. Styles without an image folder yet just get
// an empty array. Add or remove a file in a style's folder, then rerun this.
// Run: npm run tokens

const fs = require("fs");
const path = require("path");
const { getAllowedStyles, folderNameForStyle } = require("./lib/styles");

const ROOT_DIR = path.join(__dirname, "..");
const OPTIMIZED_DIR = path.join(ROOT_DIR, "images-optimized");
const FALLBACK_DIR = path.join(ROOT_DIR, "images");
const OUT_FILE = path.join(ROOT_DIR, "js", "tokens.js");
const IMG_RE = /\.(webp|png|jpe?g)$/i;

function tokensForStyle(style) {
  const folder = folderNameForStyle(style);
  const optimizedDir = path.join(OPTIMIZED_DIR, folder);
  const fallbackDir = path.join(FALLBACK_DIR, folder);
  const dir = fs.existsSync(optimizedDir) ? optimizedDir : fallbackDir;

  if (!fs.existsSync(dir)) {
    return { style, files: [], source: null };
  }

  const files = fs
    .readdirSync(dir)
    .filter((f) => IMG_RE.test(f))
    .sort((a, b) => a.localeCompare(b));

  return { style, files, source: path.relative(ROOT_DIR, dir) };
}

function main() {
  const results = getAllowedStyles().map(tokensForStyle);

  const styleArrays = results
    .map(({ style, files }) => {
      const entries = files
        .map((file) => {
          const name = file.replace(IMG_RE, "");
          return `    { name: ${JSON.stringify(name)}, file: ${JSON.stringify(file)} },`;
        })
        .join("\n");
      return `  ${JSON.stringify(style)}: [\n${entries}\n  ],`;
    })
    .join("\n");

  const contents = `// Generated by scripts/generate-tokens.js — do not edit by hand.
// One array per art style (see ALLOWED_STYLES in worker/src/config.js).
// Add or remove images in images-optimized/<Style>/ (or images/<Style>/ before
// running npm run optimize), then run: npm run tokens
const TOKENS = {
${styleArrays}
};
`;

  fs.writeFileSync(OUT_FILE, contents);

  results.forEach(({ style, files, source }) => {
    const sourceNote = source ? `source: ${source}/` : "no folder found yet";
    console.log(`${style}: wrote ${files.length} tokens (${sourceNote})`);
  });
  console.log(`\nWrote ${OUT_FILE}`);
}

main();
