name = "token-vault-generator"
main = "src/index.js"
compatibility_date = "2026-07-22"

[[r2_buckets]]
binding = "TOKEN_BUCKET"
bucket_name = "token-vault-images"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "b3048eab0cb74a578258d4312422cf14"

[[kv_namespaces]]
binding = "FEEDBACK"
id = "f38ecc82f4774b15a48bdb38bbb19398"

[observability]
enabled = true
